# Training a Simple LUTNN

In [8]:
import torch
import torch.optim as optim
from lutnn.lutlayer import LUTLayer, Aggregation

In [9]:
from utils.uci_datasets import BreastCancerDataset
import torch

train_set = BreastCancerDataset('./data-uci', split='train', download=True, with_val=False)
test_set = BreastCancerDataset('./data-uci', split='test', with_val=False)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=128, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=int(1e6), shuffle=False)
input_dim_dataset = 51
num_classes = 2

In [10]:
# Define a simple LUTNN
class SimpleLUTNN(torch.nn.Module):
    def __init__(self):
        super(SimpleLUTNN, self).__init__()
        self.layer1 = LUTLayer(input_dim=51, lut_size=4, n_luts=1024)
        self.layer2 = LUTLayer(input_dim=1024, lut_size=4, n_luts=512)
        self.layer3 = Aggregation(num_classes=2, tau=10.)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model = SimpleLUTNN().to(device)
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

cpu


In [12]:
# Training loop
num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        
        # Forward pass
        outputs = model(data)
        loss = criterion(outputs, target)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch_idx % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{batch_idx}/{len(train_loader)}], Loss: {loss.item():.4f}')

# Evaluation
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        total += target.size(0)
        correct += (predicted == target).sum().item()

print(f'Test Accuracy: {100 * correct / total:.2f}%')

Epoch [1/50], Step [0/2], Loss: 0.7066
Epoch [2/50], Step [0/2], Loss: 0.6036
Epoch [3/50], Step [0/2], Loss: 0.5712
Epoch [4/50], Step [0/2], Loss: 0.6300
Epoch [5/50], Step [0/2], Loss: 0.5256
Epoch [6/50], Step [0/2], Loss: 0.6100
Epoch [7/50], Step [0/2], Loss: 0.5759
Epoch [8/50], Step [0/2], Loss: 0.5286
Epoch [9/50], Step [0/2], Loss: 0.4743
Epoch [10/50], Step [0/2], Loss: 0.5008
Epoch [11/50], Step [0/2], Loss: 0.4850
Epoch [12/50], Step [0/2], Loss: 0.4768
Epoch [13/50], Step [0/2], Loss: 0.4754
Epoch [14/50], Step [0/2], Loss: 0.4546
Epoch [15/50], Step [0/2], Loss: 0.4598
Epoch [16/50], Step [0/2], Loss: 0.4438
Epoch [17/50], Step [0/2], Loss: 0.4327
Epoch [18/50], Step [0/2], Loss: 0.4014
Epoch [19/50], Step [0/2], Loss: 0.4304
Epoch [20/50], Step [0/2], Loss: 0.4288
Epoch [21/50], Step [0/2], Loss: 0.4249
Epoch [22/50], Step [0/2], Loss: 0.3702
Epoch [23/50], Step [0/2], Loss: 0.4007
Epoch [24/50], Step [0/2], Loss: 0.4012
Epoch [25/50], Step [0/2], Loss: 0.4001
Epoch [26

In [13]:
# VHDL generation
import os
os.chdir('/Users/rhuang/Documents/llnn-ece-x10')  # ensure we're in the project root

from hdl.convert2vhdl import get_model_params, gen_vhdl_code

# Wrap the layers so the HDL export functions can find them
model.model = torch.nn.Sequential(
    torch.nn.Flatten(),
    model.layer1,
    model.layer2,
    model.layer3
)

number_of_layers, num_neurons, lut_sizes, number_of_inputs, number_of_classes = get_model_params(model)
model_name = 'breast_lutnn'

gen_vhdl_code(model, model_name, number_of_layers, number_of_classes, number_of_inputs, num_neurons, lut_sizes)
print(f'VHDL code generated in data/VHDL/{model_name}/')

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): LUTLayer(num_luts=1024, lut_size=4)
  (2): LUTLayer(num_luts=512, lut_size=4)
  (3): Aggregation(num_classes=2, tau=10.0)
)
tensor([[0, 0, 1,  ..., 0, 1, 1],
        [0, 1, 0,  ..., 1, 0, 0],
        [1, 0, 1,  ..., 1, 1, 0],
        ...,
        [1, 0, 1,  ..., 0, 1, 0],
        [0, 1, 1,  ..., 0, 0, 1],
        [1, 1, 0,  ..., 1, 0, 0]])
tensor([[0, 0, 0,  ..., 0, 1, 1],
        [1, 0, 0,  ..., 0, 1, 0],
        [1, 1, 1,  ..., 1, 0, 1],
        ...,
        [1, 0, 1,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 1, 0, 1]])
VHDL code generated in data/VHDL/breast_lutnn/


In [14]:
# SV generation
from hdl.convert2sv import gen_sv_code

gen_sv_code(model, model_name, number_of_layers, number_of_classes, number_of_inputs, num_neurons, lut_sizes)
print(f'SystemVerilog code generated in data/sv/{model_name}/')

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): LUTLayer(num_luts=1024, lut_size=4)
  (2): LUTLayer(num_luts=512, lut_size=4)
  (3): Aggregation(num_classes=2, tau=10.0)
)
tensor([[0, 0, 1,  ..., 0, 1, 1],
        [0, 1, 0,  ..., 1, 0, 0],
        [1, 0, 1,  ..., 1, 1, 0],
        ...,
        [1, 0, 1,  ..., 0, 1, 0],
        [0, 1, 1,  ..., 0, 0, 1],
        [1, 1, 0,  ..., 1, 0, 0]])
tensor([[0, 0, 0,  ..., 0, 1, 1],
        [1, 0, 0,  ..., 0, 1, 0],
        [1, 1, 1,  ..., 1, 0, 1],
        ...,
        [1, 0, 1,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 1, 0, 1]])
SystemVerilog code generated in data/sv/breast_lutnn/
